name: Deploy to NeuroSynca VPS

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Add VPS to known hosts
        run: |
          echo "89.116.212.104 ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIPx38HCAoRazUjJXPzGHBEq50Dh6G+SW216XwqTfRQV/" >> ~/.ssh/known_hosts

      - name: Deploy with Dploy
        run: |
          ssh root@89.116.212.104 <<EOF
          cd /home/neurosynca/htdocs/www.neurosynca.com
          dploy deploy
          EOF
